export type Ofs = {
  nom: string;
  commercialisateur: string | null;
  region: string;
  departements: string | null;
  lien: string | null;
  telephone: string | null;
  email: string | null;
  isPartner: boolean;
};

export const ofss: Ofs[] = [
  {
    nom: 'OFIS',
    commercialisateur: 'Haute-Savoie Habitat',
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Haute-Savoie',
    lien: 'https://www.hautesavoiehabitat.fr/nous-connaitre/nos-marques-et-filiales/ofis/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'ORSOL',
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Isère, Rhône, Métropole de Lyon, Savoie',
    lien: 'https://orsol-brs.fr/references-projets/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Foncière Solidaire du Grand Lyon ',
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Métropole de Lyon',
    lien: 'https://www.grandlyon.com/services/habitat-et-logement/bail-reel-solidaire',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: "SD'SOL",
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Isère',
    lien: 'https://sdaccess.fr/programmes-neufs/',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: '3F Immobilière Rhône Alpes',
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Haute-Savoie',
    lien: 'https://www.cityloger.fr/immobiliere-rhone-alpes/logement-a-vendre-6197',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'Grand Lyon Habitat',
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Métropole de Lyon',
    lien: 'https://www.grandlyonhabitat.fr/je-cherche-un-bien/devenir-proprietaire/offres-de-vente/',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'Lyon métropole Habitat',
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Métropole de Lyon',
    lien: 'https://www.lmhabitat.fr/home/rechercher-un-bien/acheter-un-bien/bail-reel-solidaire-brs.html',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'OPAC du Rhône',
    commercialisateur: 'Rhône Habitat',
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Rhône, Métropole de Lyon',
    lien: 'https://www.rhonehabitat.fr/je-veux-acheter/nos-biens-disponibles',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'OPH de Haute-Savoie',
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Haute-Savoie',
    lien: 'https://www.hautesavoiehabitat.fr/louer-et-acheter/acheter/bail-reel-solidaire-brs/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'VALRIM',
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Isère, Drôme',
    lien: 'https://www.valrim-immobilier.com/bail-reel-solidaire/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Halpades',
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Haute-Savoie, Savoie, Ain',
    lien: 'https://www.halpades.fr/je-souhaite-acheter/comment-acheter-un-logement-social/',
    telephone: null,
    email: 'accession@halpades.fr',
    isPartner: true,
  },
  {
    nom: 'Cristal Habitat',
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Savoie',
    lien: 'https://www.cristal-h.fr/achat/programmes-neufs/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Alliade Habitat',
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Rhône, Métropole de Lyon, Haute-Loire',
    lien: 'https://allaccess.immo/',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'Sô Alpes',
    commercialisateur: 'S.A Mont-Blanc',
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Haute-Savoie',
    lien: 'https://www.samontblanc.com/accession-1155',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'Alpes Isère Habitat ',
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Isère',
    lien: 'https://dauphilogis.fr/nos-programmes-neufs/',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'Foncier Coopératif Malouin',
    commercialisateur: null,
    region: 'Bretagne',
    departements: 'Ille-et-Vilaine',
    lien: 'https://www.foncier-cooperatif-malouin.coop/',
    telephone: null,
    email: 'contact.fcm@keredes.coop',
    isPartner: false,
  },
  {
    nom: 'Aiguillon Construction',
    commercialisateur: null,
    region: 'Bretagne',
    departements: 'Ille-et-Vilaine',
    lien: 'https://www.imoja.fr/habiter/bien-a-acheter/',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'Keredes',
    commercialisateur: null,
    region: 'Bretagne',
    departements: 'Ille-et-Vilaine',
    lien: 'https://www.keredes.coop/achat/neuf',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'Archipel Habitat',
    commercialisateur: null,
    region: 'Bretagne',
    departements: 'Ille-et-Vilaine',
    lien: 'https://www.archipel-habitat.fr/trouver-un-logement/acheter-un-logement/programmes-en-cours',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'Morbihan Habitat',
    commercialisateur: null,
    region: 'Bretagne',
    departements: 'Morbihan',
    lien: 'https://www.morbihan-habitat.fr/achetez-un-bien-neuf/',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'Emeraude Habitation',
    commercialisateur: null,
    region: 'Bretagne',
    departements: 'Ille-et-Vilaine',
    lien: 'https://www.emeraude-habitation.fr/je-veux-acheter/biens-a-vendre/',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'Procivis Bretagne Ouest',
    commercialisateur: null,
    region: 'Bretagne',
    departements: 'Ille-et-Vilaine',
    lien: 'https://procivis.fr/notre-reseau/un-reseau-ancre/nos-sacicap/procivis-bretagne/',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'Neotoa',
    commercialisateur: null,
    region: 'Bretagne',
    departements: 'Ille-et-Vilaine',
    lien: 'https://www.neotoa.fr/recherche',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'OFS Grand Ouest',
    commercialisateur: 'Touraine Logement',
    region: 'Centre-Val de Loire',
    departements: 'Indre-et-Loire',
    lien: 'https://www.touraine-logement-promoteur.fr/programme/evidence.html',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'OFS France Loire',
    commercialisateur: null,
    region: 'Centre-Val de Loire',
    departements: null,
    lien: 'https://www.franceloire.fr/offres-de-vente',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: '3F Centre-Val de Loire',
    commercialisateur: null,
    region: 'Centre-Val de Loire',
    departements: null,
    lien: 'https://www.cityloger.fr/3f-centre-val-de-loire/logements-a-vendre',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'Valloire Habitat',
    commercialisateur: null,
    region: 'Centre-Val de Loire',
    departements: null,
    lien: 'https://www.valloire-habitat.com/LE-BRS/',
    telephone: '0238540404',
    email: 'accession@valloire-habitat.com',
    isPartner: false,
  },
  {
    nom: "Habitat de l'Ill",
    commercialisateur: null,
    region: 'Grand Est',
    departements: null,
    lien: 'https://habitatdelill.com/appartements-a-vendre/',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: "L'OFS d'Alsace",
    commercialisateur: null,
    region: 'Grand Est',
    departements: null,
    lien: 'https://www.ofsa.alsace/operations/',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'Le Foyer Rémois',
    commercialisateur: null,
    region: 'Grand Est',
    departements: null,
    lien: 'https://www.foyer-remois.fr/acheter-un-bien-avec-le-foyer-remois',
    telephone: null,
    email: null,
    isPartner: false,
  },
  {
    nom: 'OFS de la métropole de Lille',
    commercialisateur: null,
    region: 'Hauts-de-France',
    departements: null,
    lien: 'https://ofsml.fr/acheter/programmes/',
    telephone: '0320495051',
    email: 'contact@ofsml.fr',
    isPartner: false,
  },
  {
    nom: 'AMSOM',
    commercialisateur: null,
    region: 'Hauts-de-France',
    departements: null,
    lien: 'https://amsom-habitat.fr/devenir-proprietaire-3/',
    telephone: null,
    email: 'vente@amsom-habitat.fr',
    isPartner: false,
  },
  {
    nom: 'La Coop Foncière Francilienne',
    commercialisateur: null,
    region: 'Île-de-France',
    departements:
      "Seine-et-Marne, Yvelines, Hauts-de-Seine, Seine-Saint-Denis, Val-d'Oise",
    lien: 'https://coopfoncierefrancilienne.fr/nos-programmes/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Seqens',
    commercialisateur: null,
    region: 'Île-de-France',
    departements:
      "Seine-et-Marne, Yvelines, Essone, Hauts-de-Seine, Seine-Saint-Denis, Val-d'Oise",
    lien: 'https://seqens-accession.fr/programmes-en-vente/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'OFS Plaine commune',
    commercialisateur: null,
    region: 'Île-de-France',
    departements: 'Seine-Saint-Denis',
    lien: 'https://plainecommune.fr/ofs/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Foncière de la Ville de Paris',
    commercialisateur: null,
    region: 'Île-de-France',
    departements: 'Paris',
    lien: 'https://fonciere-ville-paris.fr/operations/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'OFS des Yvelines',
    commercialisateur: null,
    region: 'Île-de-France',
    departements: 'Yvelines',
    lien: 'https://www.yvelines.fr/cadre-de-vie/logement/loffice-foncier-solidaire-des-yvelines/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'OFS I3F',
    commercialisateur: null,
    region: 'Île-de-France',
    departements: null,
    lien: 'http:/www.unisson-3faccession.com/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Domofrance',
    commercialisateur: 'Exterra',
    region: 'Nouvelle-Aquitaine',
    departements: null,
    lien: 'https://www.exterra.fr/programmes',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Le Col',
    commercialisateur: null,
    region: 'Nouvelle-Aquitaine',
    departements: null,
    lien: 'https://www.acheteraucol.com/contact/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Le Col',
    commercialisateur: null,
    region: 'Occitanie',
    departements: null,
    lien: 'https://www.acheteraucol.com/contact/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: "L'EPFL des Pays-Basques - Bizitegia",
    commercialisateur: null,
    region: 'Nouvelle-Aquitaine',
    departements: null,
    lien: 'https://bizitegia.epfl-pb.fr/nos-operations/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Habitat Sud Atlantic',
    commercialisateur: null,
    region: 'Nouvelle-Aquitaine',
    departements: null,
    lien: 'https://immobilier.habitatsudatlantic.fr/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Terra Noé',
    commercialisateur: null,
    region: 'Nouvelle-Aquitaine',
    departements: null,
    lien: 'https://terra-noe.fr/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Terra Noé',
    commercialisateur: null,
    region: 'Pays de la Loire',
    departements: null,
    lien: 'https://terra-noe.fr/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Gironde Habitat - G Logis',
    commercialisateur: null,
    region: 'Nouvelle-Aquitaine',
    departements: 'Gironde',
    lien: 'https://vente.gironde-habitat.fr/achat-maisons-appartements/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Logéo Seine',
    commercialisateur: null,
    region: 'Normandie',
    departements: 'Seine-Maritime',
    lien: 'https://www.logeo-promotion.fr/logements',
    telephone: '0677846694',
    email: 'logeo-promotion@logeo.fr',
    isPartner: false,
  },
  {
    nom: 'Caen La mer',
    commercialisateur: null,
    region: 'Normandie',
    departements: null,
    lien: 'https://caenlamer.fr/ofs',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Cif Coopérative',
    commercialisateur: null,
    region: 'Normandie',
    departements: null,
    lien: 'https://www.groupecif.com/recherche/resultats/programmes-neufs',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Occitalys Foncier',
    commercialisateur: 'Les Chalets Accession',
    region: 'Occitanie',
    departements: 'Ariège, Haute-Garonne, Hautes-Pyrénées, Tarn-et-Garonne',
    lien: 'https://www.leschaletsaccession.com/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Occitalys Foncier',
    commercialisateur: 'Notre Maison - Groupe Valophis',
    region: 'Occitanie',
    departements: 'Haute-Garonne',
    lien: 'https://valophis-notremaison.fr/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Un toit pour tous - Solenterra',
    commercialisateur: null,
    region: 'Occitanie',
    departements: null,
    lien: 'https://www.untoitpourtous.fr/acheter/nos-biens-a-la-vente/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'ACM',
    commercialisateur: null,
    region: 'Occitanie',
    departements: null,
    lien: 'https://acmhabitat.fr/jplatform/jcms/sng_2000753/fr/acheter',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: "L'OFS de Montpellier Métropole",
    commercialisateur: null,
    region: 'Occitanie',
    departements: null,
    lien: 'https://www.ofs-montpellier.fr/nos-programmes-immobiliers',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Promologis',
    commercialisateur: 'Zelidom',
    region: 'Occitanie',
    departements: null,
    lien: 'https://www.zelidom.fr/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'OFS Vendée Habitat',
    commercialisateur: null,
    region: 'Pays de la Loire',
    departements: null,
    lien: 'https://vendeefonciersolidaire.fr/programme/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'OFS Racines',
    commercialisateur: 'ICEO',
    region: 'Pays de la Loire',
    departements: null,
    lien: 'https://www.iceo-habitat.fr/programme/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Tous Propriétaires',
    commercialisateur: null,
    region: "Provence-Alpes-Côte d'Azur",
    departements: null,
    lien: 'https://ofstousproprietaires.fr/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Erilia',
    commercialisateur: null,
    region: "Provence-Alpes-Côte d'Azur",
    departements: null,
    lien: 'https://www.erilia.fr/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'OFS Procivis Sud',
    commercialisateur: null,
    region: "Provence-Alpes-Côte d'Azur",
    departements: null,
    lien: 'https://procivisprovence.fr/nos_programmes/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'La Coop Foncière Méditerranée ',
    commercialisateur: 'Maison Familiale de Provence, Grand Delta Habitat',
    region: "Provence-Alpes-Côte d'Azur",
    departements: null,
    lien: 'https://maison-familiale-de-provence.fr/, https://www.granddelta.fr/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Groupe CIB',
    commercialisateur: 'Secib Immobilier',
    region: 'Bretagne',
    departements: "Finistère, Côtes d'Armor, Ille-et-Vilaine, Morbihan",
    lien: 'https://secib-immobilier.com',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'OFS de Golfe du Morbihan Vannes - agglomération',
    commercialisateur: null,
    region: 'Bretagne',
    departements: 'Morbihan',
    lien: 'https://www.ofsgmva.bzh/',
    telephone: null,
    email: 'ofs@gmvagglo.bzh',
    isPartner: false,
  },
  {
    nom: 'STON',
    commercialisateur: 'Eclisse Promotion',
    region: 'Occitanie',
    departements: 'Haute-Garonne',
    lien: 'https://www.eclisse-promotion.fr',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Icade Pierre Pour Tous',
    commercialisateur: 'Icade Promotion',
    region: 'Auvergne-Rhône-Alpes',
    departements: null,
    lien: 'https://www.icade-immobilier.com',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Breizh Coop',
    commercialisateur: null,
    region: 'Bretagne',
    departements: null,
    lien: 'https://www.lelogisbreton.bzh/logis-news/devenez-proprietaire-grace-au-bail-reel-solidaire/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Tisserin Foncière Solidaire',
    commercialisateur: 'Nacarat, Tisserin Promotion ',
    region: 'Hauts-de-France',
    departements: null,
    lien: 'https://nacarat.com, https://www.tisserin-promotion.com',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Coop Habitat',
    commercialisateur: null,
    region: 'Bretagne',
    departements: null,
    lien: 'https://www.coophabitat.fr/nos-programmes/',
    telephone: '02 99 65 41 55',
    email: 'chbrennes@coophabitat.fr',
    isPartner: false,
  },
  {
    nom: 'Foncière Solucia Territoires',
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: null,
    lien: null,
    telephone: '06 50 59 31 05',
    email: 'contact@ofs-fst.fr',
    isPartner: false,
  },
  {
    nom: 'Foncière Solucia Territoires',
    commercialisateur: null,
    region: "Provence-Alpes-Côte d'Azur",
    departements: null,
    lien: null,
    telephone: '06 50 59 31 05',
    email: 'contact@ofs-fst.fr',
    isPartner: false,
  },
  {
    nom: 'Foncière Solucia Territoires',
    commercialisateur: null,
    region: 'Nouvelle-Aquitaine',
    departements: null,
    lien: null,
    telephone: '06 50 59 31 05',
    email: 'contact@ofs-fst.fr',
    isPartner: false,
  },
  {
    nom: 'Foncière Solucia Territoires',
    commercialisateur: null,
    region: 'Pays de la Loire',
    departements: null,
    lien: null,
    telephone: '06 50 59 31 05',
    email: 'contact@ofs-fst.fr',
    isPartner: false,
  },
  {
    nom: 'Foncière Solucia Territoires',
    commercialisateur: null,
    region: 'Bretagne',
    departements: null,
    lien: null,
    telephone: '06 50 59 31 05',
    email: 'contact@ofs-fst.fr',
    isPartner: false,
  },
  {
    nom: 'OFS de Habitat et Humanisme',
    commercialisateur: 'Runimmo, Neovarim, CMKC',
    region: 'Île-de-France',
    departements:
      'Paris, Seine-et-Marne, Yvelines, Essonne, Hauts-de-Seine, Seine-Saint-Denis, Val-de-Marne',
    lien: 'https://www.runimmo.fr,  https://www.neovarim.com/nos-programmes?reinit=true, https://www.cmkc.fr/programmes/',
    telephone: null,
    email: 'Idf.ofshh@habitat-humanisme.org',
    isPartner: false,
  },
  {
    nom: 'OFS de Habitat et Humanisme',
    commercialisateur: null,
    region: 'Grand Est',
    departements: 'Bas-Rhin, Haut-Rhin',
    lien: null,
    telephone: null,
    email: 'Idf.ofshh@habitat-humanisme.org',
    isPartner: false,
  },
  {
    nom: 'La Foncière 74',
    commercialisateur: null,
    region: 'Auvergne-Rhône-Alpes',
    departements: 'Haute-Savoie',
    lien: 'https://lafonciere74.fr/logements-brs/',
    telephone: null,
    email: 'lafonciere74@lafonciere74.fr',
    isPartner: false,
  },
  {
    nom: 'OFS Procivis Nouvelle-Aquitaine',
    commercialisateur: null,
    region: 'Nouvelle-Aquitaine',
    departements:
      'Gironde, Landes, Pyrénées-Atlantiques, Charente-Maritime, Dordogne',
    lien: 'https://groupe-procivis-na.fr/lhabitat-social/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'FDI Foncier Solidaire',
    commercialisateur: null,
    region: 'Occitanie',
    departements: 'Hérault, Gard',
    lien: 'https://www.fdi-habitat.fr/devenir-proprietaire/guide-bail-reel-solidaire',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'FDI Foncier Solidaire',
    commercialisateur: null,
    region: "Provence-Alpes-Côte d'Azur",
    departements: 'Var, Alpes-Maritimes, Bouches-du-Rhône',
    lien: 'https://www.fdi-habitat.fr/devenir-proprietaire/guide-bail-reel-solidaire',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'OFS Procivis Bretagne Ouest',
    commercialisateur: 'Polimmo',
    region: 'Bretagne',
    departements: 'Finistère, Morbihan',
    lien: 'https://www.polimmo.fr/immobilier-neuf/',
    telephone: null,
    email: null,
    isPartner: true,
  },
  {
    nom: 'Proviva',
    commercialisateur: null,
    region: 'Pays de la Loire',
    departements: 'Mayenne, Maine-et-Loire, Vendée, Sarthe',
    lien: 'https://www.procivis-ouest.fr/annonces/callunes-maisons-individuelles-lhuisserie/',
    telephone: null,
    email: null,
    isPartner: true,
  },
];
