name: "Install dependencies & setup database"
description: "Install dependencies, run database migrations, and seed data"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "20.18.0"

runs:
  using: "composite"

  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright browsers
      shell: bash
      run: npx playwright install --with-deps

    - name: Run database migrations
      shell: bash
      run: make migration-migrate-ci

    - name: Seed test data
      shell: bash
      run: npm run seed:test-data -w @boris/backend
