name: "Backend tests"
description: "Run backend unit and e2e tests"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "20.18.0"

runs:
  using: "composite"

  steps:
    - name: Start backend server
      shell: bash
      run: |
        npm run start:test -w @boris/backend &
        sleep 5
