name: "Install playwright"
description: "Install playwright"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "20.19.0"

runs:
  using: "composite"

  steps:
    - name: Install Playwright browsers
      run: echo "Re enable when safe"

    # - name: Cache Playwright browsers
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       ~/.cache/ms-playwright
    #     key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
    #     restore-keys: |
    #       ${{ runner.os }}-playwright-

    # - name: Install Playwright browsers
    #   shell: bash
    #   run: npx playwright install chromium --with-deps
