version: "3.8"

services:
  database:
    image: postgres:17
    container_name: boris-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-boris}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-boris}
      POSTGRES_DB: ${POSTGRES_DB:-boris}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
