erDiagram
    %% -------------------
    %% |  RELATIONSHIPS  |
    %% -------------------

    OFS ||--|{ OFS_REGION : "se situe"
    OFS_REGION }|--|| REGION : "se situe"
    OFS ||--|{ OFS_DEPARTEMENT : "se situe"
    OFS_DEPARTEMENT }|--|| DEPARTEMENT : "se situe"
    DEPARTEMENT }|--|| REGION : "se situe"
    DISTRIBUTOR ||--o{ OFS_DISTRIBUTOR : "travaille pour"
    OFS ||--o{ OFS_DISTRIBUTOR : "travaille pour"

    %% -------------------
    %% |    ENTITIES     |
    %% -------------------

    OFS {
        string id PK
        string name
        string phone
        string websiteUrl
    }

    REGION {
      string id PK
      string name
    }

    OFS_REGION {
      string id PK
      string ofsId FK
      string regionId FK
    }

    DEPARTEMENT {
      string id PK
      string name
      string code
      string regionId FK
    }

    OFS_DEPARTEMENT {
      string id PK
      string ofsId FK
      string departementId FK
    }

    DISTRIBUTOR {
      string id PK
      string name
      string websiteUrl
    }

    OFS_DISTRIBUTOR {
      string id PK
      string ofsId FK
      string distributorId FK
    }

    USER {
      string id PK
      string email
      string password
      string firstName
      string lastName
      string role
    }

    BRS_DIFFUSION_WEBSITE {
      string id PK
      string source
      string distributorName
      string ofsName
      string city
      string zipcode
      string address
      string inseeCode
      string latitude
      string longitude
      string regionId FK
      string departementId FK
    }
