/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/regions/{id}/brs-diffusion-websites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Récupérer tous les sites web de diffusion BRS par région */
    get: operations['GetBrsDiffusionWebsitesByRegionApiController_index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/brs-diffusion-websites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Récupérer tous les sites web de diffusion BRS */
    get: operations['GetBrsDiffusionWebsitesApiController_index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/departements/{id}/brs-diffusion-websites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Récupérer tous les sites web de diffusion BRS par département */
    get: operations['GetBrsDiffusionWebsitesByDepartementApiController_index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/ofss': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Récupérer tous les OFS */
    get: operations['GetOfssApiController_index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/municipalities/{inseeCode}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Récupérer une commune par son code INSEE */
    get: operations['GetMunicipalityByInseeCodeApiController_index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/acquisition-simulations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Créer une simulation d'acquisition */
    post: operations['CreateAcquisitionSimulationApiController_createAcquisitionSimulation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/acquisition-simulations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Mettre à jour une simulation d'acquisition */
    put: operations['UpdateAcquisitionSimulationApiController_updateAcquisitionSimulation'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/acquisition-simulations/conversion-funnel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Récupérer les données du funnel de conversion du simulateur d'acquisition */
    get: operations['GetAcquisitionSimulationConversionFunnelController_index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/eligibility-simulations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Créer une simulation d'éligibilité */
    post: operations['CreateEligibilitySimulationApiController_createEligibilitySimulation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/eligibility-simulations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Mettre à jour une simulation d'éligibilité */
    put: operations['UpdateEligibilitySimulationApiController_updateEligibilitySimulation'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/landbot-customers/conversion-funnel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Récupérer les données du funnel de conversion du simulateur d'éligibilité */
    get: operations['GetLandbotCustomersConversionFunnelController_index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/landbot-customers/simulations/monthly-summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Récupérer le nombre de simulations groupées par mois */
    get: operations['GetLandbotCustomersSimulationsMonthlySummaryApiController_index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/landbot-customers/simulations/by-departements': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Récupérer le nombre de simulations groupées par départements */
    get: operations['GetLandbotCustomersGroupedByDepartementsApiController_index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/landbot-customers/simulations/by-regions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Récupérer le nombre de simulations groupées par régions */
    get: operations['GetLandbotCustomersGroupedByRegionsApiController_index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/landbot-customers/{field}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Récupérer tous les sites web de diffusion BRS groupés par un champs spécifique */
    get: operations['GetLandbotCustomersByFieldApiController_index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Pagination: {
      items: unknown[][];
      totalCount: number;
      page: number;
      pageSize: number;
      pagesCount: number;
      hasPreviousPage: boolean;
      hasNextPage: boolean;
    };
    RegionRelationnalView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example Bretagne */
      name: string;
    };
    DepartementRelationnalView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example Finistère */
      name: string;
      /** @example 29 */
      code: string;
    };
    BrsDiffusionWebsiteView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example https://source.fr */
      source: string;
      /** @example Commercialisateur du Finistère */
      distributorName: string;
      /** @example Nom de l'OFS */
      ofsName: string;
      /** @example Quimper */
      city: string;
      /** @example 29000 */
      zipcode: string;
      /** @example 29, Finistère, Bretagne */
      address: string;
      /** @example 29000 */
      inseeCode: string;
      /** @example 48.111111 */
      latitude: number;
      /** @example 4.111111 */
      longitude: number;
      /**
       * @description Distance en kilomètres
       * @example 100
       */
      distance?: number;
      region: components['schemas']['RegionRelationnalView'];
      departement: components['schemas']['DepartementRelationnalView'];
    };
    DistributorRelationnalView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example Commercialisateur du Finistère */
      name: string;
      /** @example https://ofs-de-bretagne.fr */
      websiteUrl?: string;
    };
    OfsView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example OFS de Bretagne */
      name: string;
      /** @example https://ofs-de-bretagne.fr */
      websiteUrl: Record<string, never>;
      /** @example 01 02 03 04 05 */
      phone: Record<string, never>;
      /** @example contact@ofs-de-bretagne.fr */
      email: Record<string, never>;
      /** @example true */
      producesBrs: Record<string, never>;
      /** @example true */
      isPartner: Record<string, never>;
      departements: components['schemas']['DepartementRelationnalView'][];
      regions: components['schemas']['RegionRelationnalView'][];
      distributors: components['schemas']['DistributorRelationnalView'][];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    Object: Record<string, never>;
    MunicipalityView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example Quimper */
      name: string;
      /** @example 29232 */
      inseeCode: string;
      /** @example B1 */
      zone: string;
      departement: components['schemas']['DepartementRelationnalView'];
    };
    CreateAcquisitionSimulationDTO: {
      housingPrice: number;
      brsZone: string;
      surface: number;
      housingType: string;
    };
    AcquisitionSimulationView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example 250000 */
      housingPrice: number;
      /** @example A */
      brsZone: string;
      /** @example 75 */
      surface: number;
      /** @example new */
      housingType: string;
      /** @example 50000 */
      ownContribution: number;
      /** @example 8000 */
      notaryFees: number;
      /** @example 2000 */
      oneTimeExpenses: number;
      /** @example 3.5 */
      interestRate: number;
      /** @example 20 */
      loanDuration: number;
      /** @example 2 */
      inHousePeopleAmount: number;
      /** @example 45000 */
      fiscalIncome: number;
      /** @example collectiv */
      ptzType: string;
      /** @example 1500 */
      brsFees: number;
      /** @example 1200 */
      yearlyPropertyTax: number;
      /** @example 300 */
      yearlyHouseingInsurance: number;
      /** @example monthly */
      condominiumFeesFrequency: string;
      /** @example 150 */
      condominiumFees: number;
      /** @example 2000 */
      monthlyExpenses: number;
      /**
       * Format: date-time
       * @example 2026-02-26T13:51:14.122Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-02-26T13:51:14.122Z
       */
      updatedAt: string;
    };
    UpdateAcquisitionSimulationDTO: {
      housingPrice?: number;
      brsZone?: string;
      surface?: number;
      housingType?: string;
      ownContribution?: number;
      notaryFees?: number;
      oneTimeExpenses?: number;
      interestRate?: number;
      loanDuration?: number;
      inHousePeopleAmount?: number;
      fiscalIncome?: number;
      ptzType?: string;
      brsFees?: number;
      yearlyPropertyTax?: number;
      yearlyHouseingInsurance?: number;
      condominiumFeesFrequency?: string;
      condominiumFees?: number;
      monthlyExpenses?: number;
    };
    AcquisitionSimulationCalculateFunnelConversionView: {
      /** @example 105 */
      totalHouseInformations: number;
      /** @example 100 */
      totalOwnContribution: number;
      /** @example 84 */
      totalBuyingFees: number;
      /** @example 54 */
      totalLoanInformations: number;
      /** @example 32 */
      totalBrsHousingFees: number;
    };
    CreateEligibilitySimulationDTO: {
      householdSize: number;
      hasDisability: boolean;
      dependantsAmount: number;
      /** Format: date-time */
      birthday: string;
      /** Format: date-time */
      coBuyerBirthday: string;
    };
    DepartementView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example Finistère */
      name: string;
      /** @example 29 */
      code: string;
    };
    LocationView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example 48.3905 */
      latitude: number;
      /** @example -4.486 */
      longitude: number;
      /** @example Brest */
      city: string;
      /** @example 29019 */
      citycode: string;
      /** @example Brest */
      label: string;
      /** @example Brest */
      municipality: string;
      /** @example 29200 */
      postalCode: string;
      departement: components['schemas']['DepartementView'];
    };
    EligibilitySimulationView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example 2 */
      householdSize: number;
      /** @example false */
      hasDisability: boolean;
      /** @example LOCATAIRE_PRIVE */
      propertySituation: string;
      /** @example 1 */
      dependantsAmount: number;
      /**
       * Format: date-time
       * @example 2026-02-26T13:51:14.181Z
       */
      birthday: string;
      /**
       * Format: date-time
       * @example 2026-02-26T13:51:14.181Z
       */
      coBuyerBirthday: string;
      /** @example 35000 */
      taxableIncome: number;
      /** @example COMMUN */
      declarationType: string;
      /** @example 35000 */
      firstCoBuyerTaxableIncome: number;
      /** @example 28000 */
      secondCoBuyerTaxableIncome: number;
      /** @example {
       *       "category": 1,
       *       "eligibleZoneAandAbis": true,
       *       "eligibleZoneB1": false,
       *       "eligibleZoneB2andC": false
       *     } */
      eligibility: Record<string, never>;
      /** @example Jean */
      firstName: string;
      /** @example Dupont */
      lastName: string;
      /** @example jean.dupont@example.com */
      email: string;
      /** @example 0612345678 */
      phone: string;
      /** @example false */
      hasRefusedConnection: boolean;
      /** @example T3 */
      housingType: string;
      /** @example 10000 */
      contribution: number;
      /** @example 45000 */
      resources: number;
      /** @example true */
      hadBrsKnowledge: boolean;
      /** @example SALARIE_PRIVE_NON_AGRICOLE */
      employmentStatus: string;
      /** @example  */
      laposteEmployer: string;
      /** @example true */
      canSendInformationsToLaposte: boolean;
      /** @example CADRE */
      positionType: string;
      /** @example false */
      positionStage: boolean;
      /** @example true */
      hasCompanyMoreThan10Employees: boolean;
      /** @example false */
      hasCompanyMoreThan50Employees: boolean;
      /** @example true */
      allowFinancingAndOwnershipAdvices: boolean;
      /** @example CDI */
      positionContractType: string;
      locations: components['schemas']['LocationView'][];
      /**
       * Format: date-time
       * @example 2026-02-26T13:51:14.181Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-02-26T13:51:14.181Z
       */
      updatedAt: string;
    };
    UpdateEligibilitySimulationEligibilityDTO: {
      category?: number;
      eligibleZoneAandAbis?: boolean;
      eligibleZoneB1?: boolean;
      eligibleZoneB2andC?: boolean;
    };
    UpdateEligibilitySimulationLocationDTO: {
      name?: string;
      latitude?: number;
      longitude?: number;
      city?: string;
      citycode?: string;
      label?: string;
      municipality?: string;
      postalCode?: string;
    };
    UpdateEligibilitySimulationDTO: {
      householdSize?: number;
      hasDisability?: boolean;
      dependantsAmount?: number;
      /** Format: date-time */
      birthday?: string;
      /** Format: date-time */
      coBuyerBirthday?: string;
      /** @enum {string} */
      propertySituation?:
        | 'LOCATAIRE_SOCIAL'
        | 'LOCATAIRE_PRIVE'
        | 'PROPRIETAIRE'
        | 'HEBERGE'
        | 'AUTRE';
      taxableIncome?: number;
      /** @enum {string} */
      declarationType?:
        | 'SEUL_SOUHAIT_SEUL'
        | 'SEUL_SOUHAIT_PARTENAIRE'
        | 'COMMUN';
      firstCoBuyerTaxableIncome?: number;
      secondCoBuyerTaxableIncome?: number;
      eligibility?: components['schemas']['UpdateEligibilitySimulationEligibilityDTO'];
      firstName?: string;
      lastName?: string;
      email?: string;
      phone?: string;
      hasRefusedConnection?: boolean;
      /** @enum {string} */
      housingType?: 'T1' | 'T2' | 'T3' | 'T4' | 'T5';
      contribution?: number;
      resources?: number;
      hadBrsKnowledge?: boolean;
      /** @enum {string} */
      employmentStatus?:
        | 'SALARIE_PRIVE_NON_AGRICOLE'
        | 'SALARIE_AGRICOLE'
        | 'SALARIE_PUBLIC_OU_FONCTIONNAIRE'
        | 'INDEPENDANT'
        | 'SALARIE_GROUPE_LA_POSTE'
        | 'SANS_ACTIVITE_PROFESSIONNELLE'
        | 'RETRAITE';
      laposteEmployer?: string;
      canSendInformationsToLaposte?: boolean;
      /** @enum {string} */
      positionType?: 'CADRE' | 'NON_CADRE' | 'NO_CATEGORIE_PROFESSIONNELLE';
      positionStage?: boolean;
      hasCompanyMoreThan10Employees?: boolean;
      hasCompanyMoreThan50Employees?: boolean;
      allowFinancingAndOwnershipAdvices?: boolean;
      /** @enum {string} */
      positionContractType?: 'CDI' | 'CDD';
      locations?: components['schemas']['UpdateEligibilitySimulationLocationDTO'][];
    };
    LandbotCustomerCalculateFunnelConversionView: {
      /** @example 105 */
      totalSimulations: number;
      /** @example 100 */
      totalHouseholdProvided: number;
      /** @example 84 */
      totalEligble: number;
      /** @example 54 */
      totalConnectionWish: number;
      /** @example 32 */
      totalEmailProvided: number;
      /** @example 22 */
      totalDesiredCityProvided: number;
    };
    LandbotCustomerGroupSimulationsByYearAndMonthView: {
      /** @example [
       *       {
       *         "year": 2024,
       *         "month": 1,
       *         "count": 100
       *       },
       *       {
       *         "year": 2024,
       *         "month": 2,
       *         "count": 200
       *       }
       *     ] */
      data: string[];
    };
    LandbotCustomerGroupByDepartementsView: {
      /** @example [
       *       {
       *         "departementCode": "29",
       *         "count": "32"
       *       },
       *       {
       *         "departementCode": "75",
       *         "count": "18"
       *       },
       *       {
       *         "departementCode": "13",
       *         "count": "2"
       *       }
       *     ] */
      data: string[];
    };
    LandbotCustomerGroupByRegionsView: {
      /** @example [
       *       {
       *         "regionName": "Ile-de-France",
       *         "regionCode": "11",
       *         "count": "32"
       *       },
       *       {
       *         "regionName": "Provence-Alpes-Côte d'Azur",
       *         "regionCode": "93",
       *         "count": "18"
       *       },
       *       {
       *         "regionName": "Auvergne-Rhône-Alpes",
       *         "regionCode": "84",
       *         "count": "2"
       *       }
       *     ] */
      data: string[];
      /** @example 100 */
      total: number;
    };
    LandbotCustomerGroupByFieldView: {
      /** @example [
       *       {
       *         "eligibility": "1",
       *         "count": "32"
       *       },
       *       {
       *         "eligibility": "2",
       *         "count": "18"
       *       },
       *       {
       *         "eligibility": "null",
       *         "count": "2"
       *       }
       *     ] */
      data: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  GetBrsDiffusionWebsitesByRegionApiController_index: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path: {
        /** @description L'identifiant de la ressource */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items?: components['schemas']['BrsDiffusionWebsiteView'][];
            /** @example 42 */
            totalCount?: number;
            /** @example 1 */
            page?: number;
            /** @example 10 */
            pageSize?: number;
            /** @example 5 */
            pagesCount?: number;
            /** @example false */
            hasPreviousPage?: boolean;
            /** @example true */
            hasNextPage?: boolean;
          };
        };
      };
    };
  };
  GetBrsDiffusionWebsitesApiController_index: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
        /** @description La latitude du point de référence */
        latitude?: number;
        /** @description La longitude du point de référence */
        longitude?: number;
        /** @description Le rayon en kilomètres, par défaut 50km */
        radius?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items?: components['schemas']['BrsDiffusionWebsiteView'][];
            /** @example 42 */
            totalCount?: number;
            /** @example 1 */
            page?: number;
            /** @example 10 */
            pageSize?: number;
            /** @example 5 */
            pagesCount?: number;
            /** @example false */
            hasPreviousPage?: boolean;
            /** @example true */
            hasNextPage?: boolean;
          };
        };
      };
    };
  };
  GetBrsDiffusionWebsitesByDepartementApiController_index: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path: {
        /** @description L'identifiant de la ressource */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items?: components['schemas']['BrsDiffusionWebsiteView'][];
            /** @example 42 */
            totalCount?: number;
            /** @example 1 */
            page?: number;
            /** @example 10 */
            pageSize?: number;
            /** @example 5 */
            pagesCount?: number;
            /** @example false */
            hasPreviousPage?: boolean;
            /** @example true */
            hasNextPage?: boolean;
          };
        };
      };
    };
  };
  GetOfssApiController_index: {
    parameters: {
      query: {
        page?: number;
        pageSize?: number;
        isPartner: components['schemas']['Object'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items?: components['schemas']['OfsView'][];
            /** @example 42 */
            totalCount?: number;
            /** @example 1 */
            page?: number;
            /** @example 10 */
            pageSize?: number;
            /** @example 5 */
            pagesCount?: number;
            /** @example false */
            hasPreviousPage?: boolean;
            /** @example true */
            hasNextPage?: boolean;
          };
        };
      };
    };
  };
  GetMunicipalityByInseeCodeApiController_index: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        inseeCode: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MunicipalityView'];
        };
      };
    };
  };
  CreateAcquisitionSimulationApiController_createAcquisitionSimulation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateAcquisitionSimulationDTO'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AcquisitionSimulationView'];
        };
      };
    };
  };
  UpdateAcquisitionSimulationApiController_updateAcquisitionSimulation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAcquisitionSimulationDTO'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AcquisitionSimulationView'];
        };
      };
    };
  };
  GetAcquisitionSimulationConversionFunnelController_index: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Données du funnel de conversion du simulateur d'acquisition */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AcquisitionSimulationCalculateFunnelConversionView'];
        };
      };
    };
  };
  CreateEligibilitySimulationApiController_createEligibilitySimulation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateEligibilitySimulationDTO'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EligibilitySimulationView'];
        };
      };
    };
  };
  UpdateEligibilitySimulationApiController_updateEligibilitySimulation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateEligibilitySimulationDTO'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EligibilitySimulationView'];
        };
      };
    };
  };
  GetLandbotCustomersConversionFunnelController_index: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Données du funnel de conversion du simulateur d'éligibilité */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LandbotCustomerCalculateFunnelConversionView'];
        };
      };
    };
  };
  GetLandbotCustomersSimulationsMonthlySummaryApiController_index: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Nombre de simulations par mois */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LandbotCustomerGroupSimulationsByYearAndMonthView'];
        };
      };
    };
  };
  GetLandbotCustomersGroupedByDepartementsApiController_index: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Nombre de simulations groupées par départements */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LandbotCustomerGroupByDepartementsView'];
        };
      };
    };
  };
  GetLandbotCustomersGroupedByRegionsApiController_index: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Nombre de simulations groupées par régions */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LandbotCustomerGroupByRegionsView'];
        };
      };
    };
  };
  GetLandbotCustomersByFieldApiController_index: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Le champ par lequel grouper les clients Landbot */
        field: 'eligibility' | 'brs-knowledge' | 'real-estate-situation';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Clients Landbot groupés par champs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LandbotCustomerGroupByFieldView'];
        };
      };
    };
  };
}
