/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/ofss': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Récupérer tous les OFS */
    get: operations['GetAllController_index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Pagination: {
      items: unknown[][];
      totalCount: number;
      page: number;
      pageSize: number;
      pagesCount: number;
      hasPreviousPage: boolean;
      hasNextPage: boolean;
    };
    DepartementRelationnalView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example Finistère */
      name: string;
      /** @example 29 */
      code: string;
    };
    RegionRelationnalView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example Bretagne */
      name: string;
    };
    DistributorRelationnalView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example Commercialisateur du Finistère */
      name: string;
      /** @example https://ofs-de-bretagne.fr */
      websiteUrl: string;
    };
    OfsView: {
      /** @example 5d33fedc-7a06-48a4-b53d-05bf2da446dc */
      id: string;
      /** @example OFS de Bretagne */
      name: string;
      /** @example https://ofs-de-bretagne.fr */
      websiteUrl: Record<string, never>;
      /** @example 01 02 03 04 05 */
      phone: Record<string, never>;
      /** @example contact@ofs-de-bretagne.fr */
      email: Record<string, never>;
      departements: components['schemas']['DepartementRelationnalView'][];
      regions: components['schemas']['RegionRelationnalView'][];
      distributors: components['schemas']['DistributorRelationnalView'][];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  GetAllController_index: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items?: components['schemas']['OfsView'][];
            /** @example 42 */
            totalCount?: number;
            /** @example 1 */
            page?: number;
            /** @example 10 */
            pageSize?: number;
            /** @example 5 */
            pagesCount?: number;
            /** @example false */
            hasPreviousPage?: boolean;
            /** @example true */
            hasNextPage?: boolean;
          };
        };
      };
    };
  };
}
