export interface BrsDiffusionWebsite {
  source: string;
  commune: string;
  commercialisateur: string;
  ofs: string;
}

export const brsDiffusionWebsites: BrsDiffusionWebsite[] = [
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Angers',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Vannes',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Rennes',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Nantes',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Lyon',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Quimper',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Toulouse',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Le Mans',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Brest',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Saint-Nazaire',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Grenoble',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Montpellier',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Tours',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Lorient',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Cholet',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Saint-Étienne',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Lannion',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Perpignan',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Orléans',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Saint-Malo',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'La Roche-sur-Yon',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Annecy',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Nîmes',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Reims',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Dinan',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Laval',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Chambéry',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Morlaix',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Béziers',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Dijon',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Fougères',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Saint-Brieuc',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Valence',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Bordeaux',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Concarneau',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Le Havre',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Clermont-Ferrand',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Pontivy',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Albi',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Poitiers',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Lannion',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Rouen',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Aix-en-Provence',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Carcassonne',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Limoges',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Auray',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Caen',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Avignon',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Carhaix',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Tarbes',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Besançon',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Plouguerneau',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Amiens',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Marseille',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Castres',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Metz',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Plouhinec',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Le Mans',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Nice',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Douarnenez',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Alès',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Nancy',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Plouzané',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Troyes',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Toulon',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Mende',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Strasbourg',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Plougasnou',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Mulhouse',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Cannes',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
];
