export interface BrsDiffusionWebsite {
  source: string;
  commune: string;
  commercialisateur: string;
  ofs: string;
  codeInsee?: string;
}

export const brsDiffusionWebsites: BrsDiffusionWebsite[] = [
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Angers',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Vannes',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Rennes',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Nantes',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Lyon',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Quimper',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Toulouse',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Le Mans',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Brest',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Grenoble',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Montpellier',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Tours',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Lorient',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Cholet',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Saint-Étienne',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  // limit

  // Île-de-France
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Paris',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Boulogne-Billancourt',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Versailles',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Créteil',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Argenteuil',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Montreuil',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
    codeInsee: '93048',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Nanterre',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Vitry-sur-Seine',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Levallois-Perret',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Issy-les-Moulineaux',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Clichy',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Neuilly-sur-Seine',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Antony',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Vincennes',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Colombes',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Courbevoie',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Rueil-Malmaison',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Champigny-sur-Marne',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Saint-Denis',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
    codeInsee: '93066',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Aubervilliers',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Suresnes',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Puteaux',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Cergy',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Évry',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Meaux',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Massy',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
    codeInsee: '91377',
  },

  // Auvergne-Rhône-Alpes
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Villeurbanne',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Annecy',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Chambéry',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Clermont-Ferrand',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Valence',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
    codeInsee: '26362',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Vénissieux',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Caluire-et-Cuire',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Bourg-en-Bresse',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Romans-sur-Isère',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Roanne',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Voiron',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Montluçon',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Villefranche-sur-Saône',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Thonon-les-Bains',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Annemasse',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Vienne',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },

  // Nouvelle-Aquitaine
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Bordeaux',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Limoges',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Poitiers',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'La Rochelle',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
    codeInsee: '17300',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Niort',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Angoulême',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Périgueux',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Agen',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Pau',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Bayonne',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Mont-de-Marsan',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Biarritz',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Cognac',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Rochefort',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
    codeInsee: '17299',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Saintes',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Châtellerault',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Bergerac',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Brive-la-Gaillarde',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Tulle',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Guéret',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },

  // Occitanie
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Perpignan',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Nîmes',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Béziers',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Albi',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Castres',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
    codeInsee: '81065',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Tarbes',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Auch',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Cahors',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Rodez',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Millau',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Mende',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Foix',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Carcassonne',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Narbonne',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Sète',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Agde',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Lunel',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Alès',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Pamiers',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Muret',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },

  // Hauts-de-France
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Lille',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Amiens',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Roubaix',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Tourcoing',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Calais',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Dunkerque',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Valenciennes',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Villeneuve-d\'Ascq',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Douai',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Lens',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Arras',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Béthune',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Cambrai',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Maubeuge',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Boulogne-sur-Mer',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Beauvais',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Compiègne',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Creil',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Laon',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Saint-Quentin',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },

  // Grand Est
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Strasbourg',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Reims',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Metz',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Mulhouse',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Nancy',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Colmar',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Troyes',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Châlons-en-Champagne',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Épinal',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Verdun',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
    codeInsee: '55545',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Bar-le-Duc',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Charleville-Mézières',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Sedan',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Chaumont',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
    codeInsee: '52121',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Saint-Dizier',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Haguenau',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Schiltigheim',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Illkirch-Graffenstaden',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Sarreguemines',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Forbach',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },

  // Provence-Alpes-Côte d'Azur
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Marseille',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Nice',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Toulon',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Aix-en-Provence',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Antibes',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Cannes',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Avignon',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Hyères',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Arles',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Gap',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Digne-les-Bains',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Fréjus',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Grasse',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Salon-de-Provence',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Martigues',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Aubagne',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Istres',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'La Ciotat',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Orange',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Carpentras',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },

  // Normandie
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Rouen',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Le Havre',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Caen',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Cherbourg-en-Cotentin',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Évreux',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Alençon',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Dieppe',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Saint-Lô',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Bayeux',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Lisieux',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Fécamp',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Granville',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Flers',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
    codeInsee: '61169',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Avranches',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Coutances',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Vire',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Vernon',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
    codeInsee: '27681',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Louviers',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Bernay',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Pont-Audemer',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },

  // Centre-Val de Loire
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Orléans',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Bourges',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Blois',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Chartres',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Châteauroux',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Montargis',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Dreux',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Vendôme',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Romorantin-Lanthenay',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Vierzon',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Issoudun',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Pithiviers',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Gien',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Amboise',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Chinon',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Loches',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Nogent-le-Rotrou',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Châteaudun',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'La Châtre',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Le Blanc',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },

  // Bourgogne-Franche-Comté
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Dijon',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Besançon',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Belfort',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Chalon-sur-Saône',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Nevers',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Mâcon',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Auxerre',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Montbéliard',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Dole',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Lons-le-Saunier',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Vesoul',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Sens',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Beaune',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Le Creusot',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Autun',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Pontarlier',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Héricourt',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
    codeInsee: '70285',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Morteau',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Gray',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Luxeuil-les-Bains',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },

  // Bretagne (complément)
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Saint-Brieuc',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Morlaix',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Saint-Malo',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Concarneau',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Fougères',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Douarnenez',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Vitré',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Lannion',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Pontivy',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Landerneau',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Guingamp',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Carhaix-Plouguer',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Dinan',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Brest',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Redon',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Auray',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Paimpol',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Hennebont',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },
  {
    source: 'https://keredes.coop/achat/neuf/',
    commune: 'Ploërmel',
    commercialisateur: 'Keredes',
    ofs: 'Foncier Coopératif Malouin',
  },
  {
    source: 'https://www.maison-familiale-de-quimper.fr/',
    commune: 'Quimperlé',
    commercialisateur: 'Maison Familiale de Quimper',
    ofs: 'La Coop Foncière Bretonne',
  },

  // Pays de la Loire (complément)
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'La Roche-sur-Yon',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Laval',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Saint-Nazaire',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
    codeInsee: '44184',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Saumur',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Les Sables-d\'Olonne',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Challans',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Fontenay-le-Comte',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Mayenne',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Saint-Herblain',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Rezé',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Saint-Sébastien-sur-Loire',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Vertou',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Orvault',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Couëron',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Carquefou',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'La Baule-Escoublac',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Pornic',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Château-Gontier',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Ernée',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },

  // Corse
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Ajaccio',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Bastia',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Porto-Vecchio',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Bonifacio',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Calvi',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Corte',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Propriano',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'L\'Île-Rousse',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Sartène',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Ghisonaccia',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },

  // DOM - TOM
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Fort-de-France',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Pointe-à-Pitre',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Cayenne',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Saint-Denis',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
    codeInsee: '97411',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Mamoudzou',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Nouméa',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Papeete',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Les Abymes',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Le Lamentin',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Baie-Mahault',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Le Gosier',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Sainte-Anne',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
    codeInsee: '97128',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Le Marin',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Rivière-Pilote',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Saint-Joseph',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
    codeInsee: '97412',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Saint-Paul',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
    codeInsee: '97415',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Saint-Pierre',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
    codeInsee: '97416',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Le Tampon',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Saint-André',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
    codeInsee: '97409',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Saint-Louis',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
    codeInsee: '97414',
  },

  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Melun',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Pontoise',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Savigny-sur-Orge',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Palaiseau',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Corbeil-Essonnes',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Garges-lès-Gonesse',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Sartrouville',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Roissy-en-Brie',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Yerres',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Brunoy',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Ris-Orangis',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Viry-Châtillon',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Athis-Mons',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Juvisy-sur-Orge',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Montgeron',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Draveil',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Longjumeau',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Chilly-Mazarin',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Morsang-sur-Orge',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Fleury-Mérogis',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Étampes',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Arpajon',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Dourdan',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'La Ferté-Alais',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Mennecy',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Saint-Germain-lès-Corbeil',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Brétigny-sur-Orge',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Épinay-sur-Orge',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Marcoussis',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Limours',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Gif-sur-Yvette',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Orsay',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Les Ulis',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Saclay',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Bures-sur-Yvette',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Verrières-le-Buisson',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Wissous',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Antony',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Clamart',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Châtenay-Malabry',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Le Plessis-Robinson',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Sceaux',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Fontenay-aux-Roses',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Montrouge',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Malakoff',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Vanves',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Cachan',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Arcueil',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Villejuif',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'L\'Haÿ-les-Roses',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Rungis',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Chevilly-Larue',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Thiais',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Choisy-le-Roi',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Orly',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Villeneuve-le-Roi',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Ablon-sur-Seine',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Valenton',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Villeneuve-Saint-Georges',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Mandres-les-Roses',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Santeny',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'Boissy-Saint-Léger',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Limeil-Brévannes',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Bonneuil-sur-Marne',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Sucy-en-Brie',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
  {
    source: 'https://www.iceo-habitat.fr/programme/',
    commune: 'La Queue-en-Brie',
    commercialisateur: 'Iceo',
    ofs: 'OFS Racines',
  },
  {
    source: 'https://www.archipel-habitat.fr/programmes/',
    commune: 'Ormesson-sur-Marne',
    commercialisateur: 'Archipel Habitat',
    ofs: 'Archipel Habitat',
  },
  {
    source: 'https://www.granddelta.fr/achat/',
    commune: 'Le Plessis-Trévise',
    commercialisateur: 'Grand Delta Habitat',
    ofs: 'Grand Delta Habitat',
  },
  {
    source: 'https://www.habitat-cooperatif.fr/programmes/',
    commune: 'Villiers-sur-Marne',
    commercialisateur: 'Habitat Coopératif',
    ofs: 'Foncier Coopératif Sud',
  },
];
