name: "Frontend tests"
description: "Run frontend unit and e2e tests"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "20.18.0"

runs:
  using: "composite"

  steps:
    - name: Frontend unit tests
      shell: bash
      run: npm run test:unit -w @boris/frontend

    - name: Backend e2e tests
      shell: bash
      run: npm run test:e2e -w @boris/frontend
