name: Backend tests

on:
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5433
      POSTGRES_USER: boris
      POSTGRES_PASSWORD: boris
      POSTGRES_DB: boris

    strategy:
      matrix:
        node-version: [20.18.0]

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: boris-test
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U boris-test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup database
        uses: ./.github/actions/setup-database

      - name: Run backend tests
        uses: ./.github/actions/backend
