name: Backend e2e tests

on:
  pull_request:

env:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432
  POSTGRES_USER: boris
  POSTGRES_PASSWORD: boris
  POSTGRES_DB: boris

jobs:
  backend-e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test:e2e -w @boris/backend
