name: Backend e2e tests

on:
  pull_request:

env:
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5433
  POSTGRES_USER: boris
  POSTGRES_PASSWORD: boris
  POSTGRES_DB: boris

jobs:
  backend-e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U boris-test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test:e2e -w @boris/backend
