name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      LANDBOT_CONFIG_URL: ${{ secrets.LANDBOT_CONFIG_URL }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      API_URL: ${{ secrets.API_URL }}
      PUBLIC_NODE_ENV: ${{ secrets.PUBLIC_NODE_ENV }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5433
      POSTGRES_USER: boris
      POSTGRES_PASSWORD: boris
      POSTGRES_DB: boris

    strategy:
      matrix:
        node-version: [20.18.0]

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: boris
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U boris"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: mcr.microsoft.com/playwright:v1.47.0-jammy

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup database
        uses: ./.github/actions/setup-database

      - name: Run backend tests
        uses: ./.github/actions/backend

      - name: Run frontend tests
        uses: ./.github/actions/frontend

      - name: Run lighthouse
        uses: ./.github/actions/lighthouse
