name: Deploy review app to Scalingo

on:
  pull_request:

jobs:
  deploy-review-app:
    runs-on: ubuntu-latest
    env:
      SCALINGO_API_URL: api.osc-fr1.scalingo.com
      APP_NAME: 'boris-staging'
      region: 'osc-fr1'
      api_token: ${{ secrets.SCALINGO_API_TOKEN }}

    steps:
      - name: Create review app
        uses: scalingo-community/setup-scalingo@v0.1.1
      - run: scalingo --app $APP_NAME integration-link-manual-review-app ${{ github.event.number }}
        continue-on-error: true

      - name: Deploy review app
        if: always()
        run: |
          curl
            -H "Accept: application/json" -H "Content-Type: application/json" \
            - H "Authorization: Bearer $api_token" \
            -X POST https://$SCALINGO_API_URL/v1/apps/$APP_NAME/scm_repo_link/manual_review_app \
            -d '{
              "pull_request_id": ${{ github.event.number }}
            }'
