name: Deploy review app to Scalingo

on:
  pull_request:

jobs:
  deploy-review-app:
    runs-on: ubuntu-latest
    env:
      SCALINGO_API_URL: api.osc-fr1.scalingo.com
      APP_NAME: 'boris-staging'
      region: 'osc-fr1'
      api_token: ${{ secrets.SCALINGO_API_TOKEN }}
      SCALINGO_BEARER_TOKEN: ${{ secrets.SCALINGO_BEARER_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref }}

    steps:
      - name: Create review app
        uses: scalingo-community/setup-scalingo@v0.1.1
      - run: scalingo --app $APP_NAME integration-link-manual-review-app ${{ github.event.number }}
        continue-on-error: true

      - name: Deploy review app
        if: always()
        run: |
          curl -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $SCALINGO_BEARER_TOKEN" \
            -X POST https://$SCALINGO_API_URL/v1/apps/$APP_NAME-pr${{ github.event.number }}/deployments -d \
            '{
              "deployment": {
                "git_ref": "deploy-review-apps-from-github-actions",
                "source_url": "https://github.com/MTES-MCT/boris/archive/$BRANCH_NAME.tar.gz"
              }
            }'
