name: Deploy review app to Scalingo

on:
  pull_request:

jobs:
  deploy-review-app:
    runs-on: ubuntu-latest
    env:
      APP_NAME: 'boris-staging'

    steps:
      - name: Create review app
        uses: scalingo-community/setup-scalingo@v0.1.1
        with:
          region: 'osc-fr1'
          api_token: ${{ secrets.SCALINGO_API_TOKEN }}
          app_name: $APP_NAME
      - run: scalingo --app $APP_NAME integration-link-manual-review-app ${{ github.event.number }}

      - name: Deploy review app
        if: always()
        uses: scalingo-community/setup-scalingo@v0.1.1
        with:
          region: 'osc-fr1'
          api_token: ${{ secrets.SCALINGO_API_TOKEN }}
          app_name: $APP_NAME
      - run: scalingo --app $APP_NAME-pr${{ github.event.number }} integration-link-manual-deploy ${{ github.event.number }}
