name: Frontend tests

on:
  pull_request:

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    env:
      LANDBOT_CONFIG_URL: ${{ secrets.LANDBOT_CONFIG_URL }}
      PUBLIC_BORIS_CMS_URL: ${{ secrets.PUBLIC_BORIS_CMS_URL }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      API_URL: ${{ secrets.API_URL }}

    strategy:
      matrix:
        node-version: [20.18.0]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci

      - name: Frontend unit tests
        run: npm run test:unit -w @boris/frontend

      - name: Install playrwight
        run: npx playwright install --with-deps

      - name: Frontend e2e tests
        run: npm run test:e2e -w @boris/frontend
