name: Lighthouse desktop

on:
  pull_request:

jobs:
  lighthouse-desktop:
    # skip for now
    if: false
    runs-on: ubuntu-latest
    env:
      LANDBOT_CONFIG_URL: ${{ secrets.LANDBOT_CONFIG_URL }}
      PUBLIC_BORIS_CMS_URL: ${{ secrets.PUBLIC_BORIS_CMS_URL }}
    strategy:
      matrix:
        node-version: [20.x]
        runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build -w client
      - run: npm run preview -w client & npm run lighthouse-desktop -w client
      - name: Upload Lighthouse Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: lighthouse-report-${{ matrix.runs-on }}
          path: ${{ github.workspace }}/client/.lighthouseci/*
