name: Lighthouse

on:
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    env:
      LANDBOT_CONFIG_URL: ${{ secrets.LANDBOT_CONFIG_URL }}
      PUBLIC_NODE_ENV: ${{ secrets.PUBLIC_NODE_ENV }}
      API_URL: ${{ secrets.API_URL }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5433
      POSTGRES_USER: boris
      POSTGRES_PASSWORD: boris
      POSTGRES_DB: boris

    strategy:
      matrix:
        node-version: [20.18.0]

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: boris-test
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U boris-test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci

      - name: Run database migrations
        run: make migration-migrate-ci

      - name: Seed test data
        run: npm run seed:test-data -w @boris/backend

      - name: Start backend server
        run: |
          npm run start:test -w @boris/backend &
          sleep 5

      - name: Build frontend
        run: npm run build -w @boris/frontend

      - name: Start server
        run: npm run preview -w @boris/frontend &

      - name: Run lighthouse desktop
        run: npm run lighthouse-desktop -w @boris/frontend

      - name: Upload lighthouse desktop report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: lighthouse-report-ubuntu-latest
          path: ${{ github.workspace }}/apps/frontend/.lighthouseci/*

      - name: Run lighthouse mobile
        # skip for now
        if: false
        run: npm run lighthouse-mobile -w @boris/frontend

      - name: Upload lighthouse mobile report
        # skip for now
        if: false
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: lighthouse-report-ubuntu-latest
          path: ${{ github.workspace }}/apps/frontend/.lighthouseci/*
