name: Lighthouse mobile

on:
  pull_request:

jobs:
  lighthouse-mobile:
    runs-on: ubuntu-latest
    env:
      LANDBOT_CONFIG_URL: ${{ secrets.LANDBOT_CONFIG_URL }}
      PUBLIC_BORIS_CMS_URL: ${{ secrets.PUBLIC_BORIS_CMS_URL }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    strategy:
      matrix:
        node-version: [20.x]
        runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @boris/client build
      - run: yarn workspace @boris/client preview & yarn workspace @boris/client lighthouse-mobile
      - name: Upload Lighthouse Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: lighthouse-report-${{ matrix.runs-on }}
          path: ${{ github.workspace }}/client/.lighthouseci/*
